version: "{build}"

platform:
  - x86
  - x64

environment:
  matrix:
  - NODE_VERSION: 6.9.1

cache:
  - node_modules
  - app\node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

# Only build if commit message contains 'build'
# only_commits:
#   message: /build/

install:
  - ps: Install-Product node $env:NODE_VERSION $env:PLATFORM
  - npm install npm -g
  - npm install --no-optional

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - script\appveyor-build.cmd

# Post-install test scripts.
# test_script:
#   - script\test.cmd
test: off